import { Smash } from '@/types';

export const mockSmashes: Smash[] = [
  {
    id: '1',
    title: 'Fastest 5K This Weekend',
    description: 'Race to run 5K in the fastest time. GPS verified.',
    category: 'fitness',
    status: 'active',
    entryFee: 25,
    prizePool: 2500,
    creatorId: '0x123',
    participants: Array(47).fill('0x'),
    maxParticipants: 100,
    createdAt: new Date('2026-01-15'),
    startsAt: new Date('2026-01-18'),
    endsAt: new Date('2026-01-20'),
    verificationMethod: 'automated',
    proofRequirements: ['GPS data', 'Photo'],
    bettingEnabled: true,
    tags: ['running', '5k', 'weekend'],
  },
  {
    id: '2',
    title: 'Beat Elden Ring Boss Hitless',
    description: 'Defeat Malenia without taking a single hit.',
    category: 'gaming',
    status: 'active',
    entryFee: 50,
    prizePool: 1000,
    creatorId: '0x456',
    participants: Array(12).fill('0x'),
    maxParticipants: 50,
    createdAt: new Date('2026-01-16'),
    startsAt: new Date('2026-01-17'),
    endsAt: new Date('2026-01-24'),
    verificationMethod: 'creator',
    proofRequirements: ['Video recording', 'No cuts'],
    bettingEnabled: true,
    tags: ['gaming', 'elden ring', 'challenge'],
  },
  {
    id: '3',
    title: 'Best AI-Generated Cyberpunk Art',
    description: 'Create the most impressive cyberpunk cityscape using AI.',
    category: 'creative',
    status: 'active',
    entryFee: 10,
    prizePool: 500,
    creatorId: '0x789',
    participants: Array(23).fill('0x'),
    maxParticipants: 100,
    createdAt: new Date('2026-01-14'),
    startsAt: new Date('2026-01-17'),
    endsAt: new Date('2026-01-21'),
    verificationMethod: 'community-vote',
    proofRequirements: ['Image submission'],
    bettingEnabled: true,
    tags: ['art', 'ai', 'cyberpunk'],
  },
];